### ISSUE TITLE
Error after update package to 2.0.4 version

### ISSUE THREAD

**Issue by h4mit** [scttcper/toastr-ng2#31]
Hi, after update package error my project : 
```
core.umd.js:2838 EXCEPTION: Error in :0:0 caused by: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: ''. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?ErrorHandler.handleError @ core.umd.js:2838(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:232onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:231Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:264Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339
core.umd.js:2840 ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: ''. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?ErrorHandler.handleError @ core.umd.js:2840(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:232onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:231Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:264Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339
core.umd.js:2843 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.js:2843(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:232onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:231Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:264Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339
core.umd.js:2844 Error: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: ''. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at ExpressionChangedAfterItHasBeenCheckedError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:1105:38)
    at new ExpressionChangedAfterItHasBeenCheckedError (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4649:20)
    at checkBinding (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4758:23)
    at Wrapper_Toast.checkHost (/ToastrModule/Toast/wrapper.ngfactory.js:34:7)
    at CompiledTemplate.proxyViewClass.View_Toast_Host0.detectChangesInternal (/ToastrModule/Toast/host.ngfactory.js:31:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9355:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9448:48)
    at ViewRef_.checkNoChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:7341:70)
    at eval (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:6591:92)
    at Array.forEach (native)ErrorHandler.handleError @ core.umd.js:2844(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:232onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:231Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:264Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339
core.umd.js:2847 ERROR CONTEXT:ErrorHandler.handleError @ core.umd.js:2847(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:232onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:231Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:264Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339
core.umd.js:2848 DebugContext {_view: C…e.proxyViewClass, _nodeIndex: 0, _tplRow: 0, _tplCol: 0}ErrorHandler.handleError @ core.umd.js:2848(anonymous function) @ core.umd.js:6362ZoneDelegate.invoke @ zone.js:232onInvoke @ core.umd.js:5976ZoneDelegate.invoke @ zone.js:231Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265onInvokeTask @ core.umd.js:5967ZoneDelegate.invokeTask @ zone.js:264Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339
zone.js:388 Unhandled Promise rejection: Error in :0:0 caused by: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: ''. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ? ; Zone: <root> ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in :0:0 caused by: Expression has changed after it was checked. Previous value: 'CD_INI…, originalError: ExpressionChangedAfterItHasBeenCheckedError, context: DebugContext} Error: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: ''. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at ExpressionChangedAfterItHasBeenCheckedError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:1105:38)
    at new ExpressionChangedAfterItHasBeenCheckedError (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4649:20)
    at checkBinding (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4758:23)
    at Wrapper_Toast.checkHost (/ToastrModule/Toast/wrapper.ngfactory.js:34:7)
    at CompiledTemplate.proxyViewClass.View_Toast_Host0.detectChangesInternal (/ToastrModule/Toast/host.ngfactory.js:31:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9355:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9448:48)
    at ViewRef_.checkNoChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:7341:70)
    at eval (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:6591:92)
    at Array.forEach (native)consoleError @ zone.js:388_loop_1 @ zone.js:417drainMicroTaskQueue @ zone.js:421ZoneTask.invoke @ zone.js:339
zone.js:390 Error: Uncaught (in promise): Error: Error in :0:0 caused by: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: ''. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?(…)
```

my Angular versin : 2.2.4

**Comment by scttcper** [comment]
I haven't tested on 2.2.4 yet.

**Comment by scttcper** [comment]
Alright just tested it with 2.2.4 and thats not the issue.

**Comment by h4mit** [comment]
but, removed ToastrModule as NgModule fixed bug in the project.

**Comment by scttcper** [comment]
How were you using the toast?

**Comment by h4mit** [comment]
```
 constructor(private toastrService: ToastrService){
        this.toastrService,success("Welcome","MyProj");
 }
```

**Comment by h4mit** [comment]
downgrade package and solve problem 😣

**Comment by scttcper** [comment]
I wouldn't call the toast inside the constructor. Instead use ngOnInit() or after in the lifecycle.

**Comment by h4mit** [comment]
Tested on **ngOnInit()** but not error fixed 😢

**Comment by yarrgh** [comment]
Does that error only happen when you try to create a toast? What version of toastr-ng2 are you using?

**Comment by scttcper** [comment]
I'm not able to recreate this.
