### ISSUE TITLE
Can you please include a systemjs config file?

### ISSUE THREAD

**Issue by cmk1523** [scttcper/toastr-ng2#41]
How do you get angular2 to recognize the path: import { ToastrModule } from 'toastr-ng2'; ? Where is your systemjs config file?

**Comment by scttcper** [comment]
Released 3.2.3 that includes a UMD packed toastr.umd.js You should load this the same way you load other UMD packed packages. https://github.com/scttcper/toastr-ng2#systemjs
I copied the UMD packing config from ng-bootstrap and didn't test it, good luck.

**Comment by yarrgh** [comment]
Is there an issue with npm or did you unpublish 3.2.3? I cannot install it to test this.

**Comment by scttcper** [comment]
@yarrgh looks like it didn't go. Try again now.

**Comment by clabough** [comment]
toastr.umd.js came down for me just now

**Comment by clabough** [comment]
that umd.js file isn't going to work. It's designed for bootstrap.  It throws errors like "Cannot read property 'defaultDoc' of null"

**Comment by yarrgh** [comment]
Full error:

```
TypeError: Cannot read property 'defaultDoc' of null
    at _document (http://localhost:3000/node_modules/toastr-ng2/toastr.umd.js:3238:101)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:39:83)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:74:106)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:79:110)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:99:87)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:244:49)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:8913:48)
    at ComponentFactory.create (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:7700:48)
    at ApplicationRef_.bootstrap (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:8672:61)
    at eval (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:8501:93)
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:8501:46)
    at eval (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:8453:31)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:229:26)
    at Object.onInvoke (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4405:41)
```

**Comment by scttcper** [comment]
Dang... what is defaultdoc... How are you guys testing this? Are there other packages that do this?

@clabough I see what you're saying theres a DomAdapter in there and stuff.

**Comment by yarrgh** [comment]
I'm using the [quickstart](https://github.com/angular/quickstart)

**Comment by yarrgh** [comment]
I have a sort of working umd file. I compiled the source like normal but modified the rollup.js file to the following:

```javascript
export default {
  entry: './deploy/toastr.js',
  dest: './deploy/toastr.umd.js',
  format: 'umd',
  moduleName: 'toastrng2',
  globals: {
    '@angular/core': 'ng.core',
    '@angular/compiler': 'ng.compiler',
    '@angular/platform-browser': 'ng.platformBrowser',
    '@angular/http': 'ng.http',
    'rxjs/Observable': 'Rx',
    'rxjs/Subject': 'Rx'
  }
};
```

And then used rollup to target that rollup.js as a config file. For example `node_modules\.bin\rollup -c rollup.js`.

The umd file is now much leaner and works correctly with systemjs.

**Comment by yarrgh** [comment]
If you want I can create a pull request for you to review

**Comment by scttcper** [comment]
Yeah, please do.

**Comment by clabough** [comment]
That's looking pretty good to me so far.

**Comment by scttcper** [comment]
released 3.2.4

**Comment by yarrgh** [comment]
So far it's working great with the quickstart app. 

@clabough @cmk1523 can you guys install 3.2.4 and make sure it works in your projects?

**Comment by clabough** [comment]
working for me. thank you.
